INSERT INTO plants_db.products(category_id, description, name, price, image_url, light, water, soil, pet_safety)
VALUES (1,
        'The snake plant is a great choice for a hardy houseplant that can thrive without much attention. A large succulent with stiff, vertical leaves, it can go without water for weeks at a time. It''s tolerant of a wide variety of conditions, from bright light to shade and dry to humid air.',
        'Snake Plant (Sansevieria trifasciata)', 5.99,
        'https://res.cloudinary.com/lorayonova/image/upload/v1658912963/plants/Treehugger-Test32131-3dd182ef50d6443da6a9be3b05b20bd8_lays1p.webp',
        'Medium, indirect light; tolerates sun and shade.',
        'Water regularly, allowing soil to dry well before re-watering.',
        'Rich, well-draining potting mix.',
        'Toxic to cats and dogs.'),
       (1,
        'The parlor palm has long been a popular houseplant choice, and for good reason. This shade-tolerant native of Central and South America grows two to three feet tall at maturity, tolerates low light, and requires only infrequent watering. All this makes it a great choice for beginners or forgetful plant owners. Parlor palms are also sometimes called bamboo palms because of their bamboo-like stems, and they produce inedible fruits (though fruiting is rare indoors).',
        'Parlor Palm (Chamaedorea elegans)', 10.99,
        'https://res.cloudinary.com/lorayonova/image/upload/v1658913011/plants/16404871208_7a96de6d1d_c-85006ee2d2a34d899751888ddbcce982_jpgjbp.webp',
        'Ideally moderate-bright indirect light, can tolerate low light; avoid direct sun.',
        'Important not to overwater; wait one or two weeks depending on plant location.',
        'Peat-based potting mix; does not tolerate salt.',
        'Nontoxic to cats and dogs.'),
       (1,
        'The spider plant, also known as the ribbon plant, is a forgiving houseplant, especially when it comes to infrequent watering and artificial light. It grows well in pots or hanging baskets and is easily propagated by division, offering the option to grow more plants for the price of one. With distinctive light green stripes on its leaves and white, starlike flowers, it makes for a showy houseplant, even when it gets less attention than it deserves.',
        'Spider Plant (Chlorophytum comosum)', 7.99,
        'https://res.cloudinary.com/lorayonova/image/upload/v1658913060/plants/328A5880-85f44f681934498990e792036740667a_crawke.webp',
        'Bright, indirect sunlight.',
        'When soil is dry; this is usually infrequently.',
        'Well-drained, standard potting mix.',
        'Nontoxic to cats and dogs.'),
       (1,
        'The eternity plant really lives up to its name. It thrives in less than perfect conditions, outlasting poor plant care for what can seem like an eternity. It needs little water and low to medium light, and can exist happily even in rooms with mostly artificial lighting. It''s still best to water it, but since it prefers its soil to dry completely between doses, this can be as little as once a month.',
        'Eternity Plant (Zamioculcas zamiifolia)', 12.60,
        'https://res.cloudinary.com/lorayonova/image/upload/v1658913122/plants/croppedzz-429160f737cb487d96438b1049a0e45a_jr4jer.webp',
        'Indirect bright light is best; tolerates low light and direct light.',
        'When soil is completely dry (in some cases, as little as once monthly).',
        'Well-draining potting soil.',
        'Toxic to cats and dogs.'),
       (1,
        'The corn plant is a hardy houseplant that can do well in shadier spots in your house. It tolerates inattention fairly well and is easy to monitor, as its leaf tips will start to brown if it needs more water. It''s also a good choice as a large floor plant, since it can grow four to six feet tall at maturity. It grows slowly from canelike stalks that can be cut back to train the plant to the size you prefer.',
        'Corn Plant (Dracaena fragrans)', 17.50,
        'https://res.cloudinary.com/lorayonova/image/upload/v1658913160/plants/large-indoor-plants-5094187_corn_55-4dfb0808c0d74a278a980e088a6d3ce8_folcxl.webp',
        'Lower to medium indirect light, filtered sun.',
        'Keep soil moist but not soggy.',
        'Rich, well-draining potting mix.',
        'Toxic to cats and dogs'),
       (1,
        'Golden pothos is a good choice as an introduction to vining houseplants. It''s known for its forgiving nature and heart-shaped leaves of yellow and green. Sometimes growing 12 to 18 inches a month, it can be trained to vine quickly and easily. Though it prefers natural light, pothos can grow well under fluorescent lighting, making it a good choice in dorm rooms, offices, or any other space with mostly artificial light.',
        'Golden Pothos (Epipremnum aureum)', 6.99,
        'https://res.cloudinary.com/lorayonova/image/upload/v1658913221/plants/pothos-c98ce75f4e604a158f5be743a837df4a_wszg3m.webp',
        ' Bright, indirect light; can tolerate partial shade or artificial light.',
        'Allow to dry completely between watering; water thoroughly if leaves droop.',
        'Ordinary potting mix that drains well.',
        'Toxic to cats and dogs.'),
       (1,
        'The peace lily is a large, attractive houseplant that is popular for its ability to withstand low light conditions. It produces white flowers, though it will produce more flowers when given ample light. In low light conditions, however, it still functions as a hardy foliage plant.',
        'Peace Lily (Spathiphyllum wallisii)', 14,
        'https://res.cloudinary.com/lorayonova/image/upload/v1658913271/plants/peacelily-9e5cdaa468e54539ad692fa03bda12dc_pvxnor.webp',
        'Filtered light; generally prefers shade or partial light.',
        'When soil is dry; roughly once a week.',
        'Rich, loose potting soil with organic material.',
        'Toxic to cats and dogs.'),
       (1,
        'Aloe is a succulent plant with thick, dark green leaves. It prefers bright light but is highly drought tolerant. On a sunny windowsill, it will thrive absent much attention. Aloe can tolerate partial light but might produce long, spindly leaves instead of strong, stout ones.',
        'Aloe (Aloe barbadensis)', 9.99,
        'https://res.cloudinary.com/lorayonova/image/upload/v1658913352/plants/croppedaloe-424bbc285079402183da48b19fda229c_qtnlyc.webp',
        'Full sun',
        'When the top two inches of soil are dry.',
        'Sandy and well-drained.',
        'Toxic to cats and dogs.'),
       (2,
        'If you have full sun or close to it, lavender is an ideal balcony plant, since it can tolerate some drier conditions once established and it''s incredibly easy to grow.
When the sun shines on it, you will smell the delightful scent of lavender wafting through your home from your balcony.',
        'English Lavender (Lavandula angustifolia)',
        3.50,
        'https://res.cloudinary.com/lorayonova/image/upload/v1659637569/plants/GettyImages-1249964974-552196b457464aa5a3705c395ccbc91e_kife8o.webp',
        'Full sun or close to it.', 'Weekly; can tolerate drier conditions once established.',
        'Regular potting soil.',
        'Toxic to cats and dogs.'),
       (2,
        'These plants are small succulents, so they are ideal as pretty soil cover in planters with taller plants in them. Since they need full sun, be sure to pair them with plants that also need that much light. They can also work well on their own in a hanging planter.',
        'Sedum or Stonecrop (Crassulaceae)',
        5.35,
        'https://res.cloudinary.com/lorayonova/image/upload/v1659637906/plants/GettyImages-883072642-d5e89848b90848bc97c6d0fe23f3e64b_vrfpqy.webp',
        'Full to half-sun.',
        'Weekly in spring, less frequently in winter.',
        'Any soil.',
        'Nontoxic to cats and dogs.'),
       (2,
        'Aloe vera is tough, doesn''t need frequent watering, and grows well in full sun to a half-day of sun. It''s also a great plant to have around for DIY beauty treatments, including a relaxing face mask.',
        'Aloe Vera (Aloe barbadensis Mill.)',
        6.20,
        'https://res.cloudinary.com/lorayonova/image/upload/v1659638367/plants/078A6145-00da10ed32dd4c89ad8385b5ac38a911_dnfrgm.webp',
        'Bright, indirect.',
        'Once every week or two, let dry out fully between watering.',
        'Well-draining, sandy.',
        'Toxic to dogs and cats.'),
       (2,
        'Orange and yellow marigold flowers are bright, happy shots of color in any garden space and ideal for a balcony planter filled with annuals. As long as they get lots of water and sun, they''ll bloom all summer long and even into autumn. Marigolds can self-seed, so you may even see some come up again the following year if you don''t change the soil.',
        'Marigold (Tagetes)',
        7.30,
        'https://res.cloudinary.com/lorayonova/image/upload/v1659638562/plants/close-up-of-orange-marigold-flowers-564749731-b14ee32b9d54481a890db949851f89cb_ztz8gz.webp',
        'Full sun.',
        'Regularly.',
        'Rich, well-drained soil.',
        'Nontoxic to cats and dogs.'),
       (2,
        'Begonias have tons of blooms all summer long if well-watered and fed, and they can overwinter in pots (though all their foliage will die).
They drape over the sides of containers gracefully, trailing leaves and flowers over the edge of whatever they''re planted in, making them a popular choice for hanging baskets. Begonias like a mix of sun and shade, and even do well in areas with more shade than sun.',
        'Begonia (Begoniaceae)',
        8.60,
        'https://res.cloudinary.com/lorayonova/image/upload/v1659640244/plants/GettyImages-857688888-ec953250efb84625ad3fe5a81faa1a0f_hajm21.webp',
        'Partially shady.',
        'Generously and regularly.',
        'Potting soil with good drainage.',
        'Toxic to cats and dogs.'),
       (2,
        'Rosemary is super hardy and will overwinter well if left outside on your balcony. Of course, you can use the fresh or dried plant in your cooking (nothing''s quite as tasty as fresh chopped rosemary and butter over roasted potatoes). But it also grows quickly and easily in full sun and can tolerate drier conditions.',
        'Rosemary (Salvia rosmarinus)',
        3.50,
        'https://res.cloudinary.com/lorayonova/image/upload/v1659640573/plants/GettyImages-760284635-f382b52c660e4771a875aad5312c0a48_lcku4g.webp',
        'Full sun.',
        ' Every one to two weeks.',
        'Light, well-draining.',
        ' Nontoxic to dogs and cats.'),
       (2,
        'If you grow some mint alongside your rosemary or lavender, you can claim a balcony herb garden—and you''ll have fresh mint for tossing in salads, or mashing up for a mojito.
Mint grows easily in containers and needs a fair amount of sun and very regular watering. If you have more shade than sun, there are a few varieties of mint that still may do well in your space—look for variegated leaves (with a white stripe or patterning on green leaves) for the shade-tolerators.',
        'Mint (Mentha sp.)',
        3.40,
        'https://res.cloudinary.com/lorayonova/image/upload/v1659640779/plants/closeupmintcopy-51b1596cc6b94f0aa15d70d7a9b745ac_keqb5r.webp',
        ' Full sun.',
        'Regularly.',
        'Potting soil.',
        'Toxic to dogs and cats.'),
       (2,
        'Hostas are often planted in the shady parts of gardens and under trees, but they can tolerate some direct sun, just not too much. They need rich soil and plenty of water, and will grow well (and overwinter) in pots, too.
Hostas have generous green leaves (some are variegated and those stripes will expand in a shady area) and sport pretty lavender blooms that shoot up above the leaves.',
        'Hosta (Hosta)',
        15.40,
        'https://res.cloudinary.com/lorayonova/image/upload/v1659641002/plants/GettyImages-1286337235-c850a68419ff4f5f8999b5ae46b9dbd8_phqzms.webp',
        'Shade to partial sun.',
        'Regularly, keep damp but not wet.',
        'Rich potting soil.',
        'Toxic to dogs and cats.'),
       (2,
        'As their name indicates, these roses do well in containers. Like all roses, they will need plenty of sun and water, as well as a rose-specific fertilizer. Other than that, they are pretty tough and won''t need much babying.
Patio roses are more compact than regular rose varieties and can stay outdoors in winter (mulch the top of the soil) as long as they are USDA hardiness rated for it.',
        'Patio Rose (Rosa Rosa)',
        9.70,
        'https://res.cloudinary.com/lorayonova/image/upload/v1659641210/plants/GettyImages-1160747064-19955d75467545a6b6c1727acecc07ca_ryotyq.webp',
        'Full sun.',
        'Regularly and deeply.',
        'Rich potting soil.',
        'Nontoxic to dogs and cats.');
